/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteRouteImport } from './routes/_profile/route'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as ProfileIndexRouteImport } from './routes/_profile/index'
import { Route as ProfileRecapRouteRouteImport } from './routes/_profile/recap/route'
import { Route as ProfileRecapIndexRouteImport } from './routes/_profile/recap/index'
import { Route as ProfileRecapLoadingRouteImport } from './routes/_profile/recap/loading'

const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/_profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileRecapRouteRoute = ProfileRecapRouteRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileRecapIndexRoute = ProfileRecapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRecapRouteRoute,
} as any)
const ProfileRecapLoadingRoute = ProfileRecapLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => ProfileRecapRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProfileIndexRoute
  '/profiles': typeof ProfilesRoute
  '/recap': typeof ProfileRecapRouteRouteWithChildren
  '/recap/loading': typeof ProfileRecapLoadingRoute
  '/recap/': typeof ProfileRecapIndexRoute
}
export interface FileRoutesByTo {
  '/profiles': typeof ProfilesRoute
  '/': typeof ProfileIndexRoute
  '/recap/loading': typeof ProfileRecapLoadingRoute
  '/recap': typeof ProfileRecapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_profile': typeof ProfileRouteRouteWithChildren
  '/profiles': typeof ProfilesRoute
  '/_profile/recap': typeof ProfileRecapRouteRouteWithChildren
  '/_profile/': typeof ProfileIndexRoute
  '/_profile/recap/loading': typeof ProfileRecapLoadingRoute
  '/_profile/recap/': typeof ProfileRecapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profiles' | '/recap' | '/recap/loading' | '/recap/'
  fileRoutesByTo: FileRoutesByTo
  to: '/profiles' | '/' | '/recap/loading' | '/recap'
  id:
    | '__root__'
    | '/_profile'
    | '/profiles'
    | '/_profile/recap'
    | '/_profile/'
    | '/_profile/recap/loading'
    | '/_profile/recap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  ProfilesRoute: typeof ProfilesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_profile': {
      id: '/_profile'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_profile/': {
      id: '/_profile/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/_profile/recap': {
      id: '/_profile/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof ProfileRecapRouteRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/_profile/recap/': {
      id: '/_profile/recap/'
      path: '/'
      fullPath: '/recap/'
      preLoaderRoute: typeof ProfileRecapIndexRouteImport
      parentRoute: typeof ProfileRecapRouteRoute
    }
    '/_profile/recap/loading': {
      id: '/_profile/recap/loading'
      path: '/loading'
      fullPath: '/recap/loading'
      preLoaderRoute: typeof ProfileRecapLoadingRouteImport
      parentRoute: typeof ProfileRecapRouteRoute
    }
  }
}

interface ProfileRecapRouteRouteChildren {
  ProfileRecapLoadingRoute: typeof ProfileRecapLoadingRoute
  ProfileRecapIndexRoute: typeof ProfileRecapIndexRoute
}

const ProfileRecapRouteRouteChildren: ProfileRecapRouteRouteChildren = {
  ProfileRecapLoadingRoute: ProfileRecapLoadingRoute,
  ProfileRecapIndexRoute: ProfileRecapIndexRoute,
}

const ProfileRecapRouteRouteWithChildren =
  ProfileRecapRouteRoute._addFileChildren(ProfileRecapRouteRouteChildren)

interface ProfileRouteRouteChildren {
  ProfileRecapRouteRoute: typeof ProfileRecapRouteRouteWithChildren
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileRecapRouteRoute: ProfileRecapRouteRouteWithChildren,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  ProfilesRoute: ProfilesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
