/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteRouteImport } from './routes/_profile/route'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as ProfileIndexRouteImport } from './routes/_profile/index'

const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/_profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProfileIndexRoute
  '/profiles': typeof ProfilesRoute
}
export interface FileRoutesByTo {
  '/profiles': typeof ProfilesRoute
  '/': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_profile': typeof ProfileRouteRouteWithChildren
  '/profiles': typeof ProfilesRoute
  '/_profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profiles'
  fileRoutesByTo: FileRoutesByTo
  to: '/profiles' | '/'
  id: '__root__' | '/_profile' | '/profiles' | '/_profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  ProfilesRoute: typeof ProfilesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_profile': {
      id: '/_profile'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_profile/': {
      id: '/_profile/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
  }
}

interface ProfileRouteRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  ProfilesRoute: ProfilesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
